routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

#Auth::routes();

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

Route::get('/home', 'HomeController@index');

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin\\'
], function() {
    Route::name('login')->get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login');

    Route::group(['middleware' => ['isVerified', 'can:admin']], function (){
        Route::get('dashboard', function () {
            return view('admin.dashboard');
        });

        Route::name('user_settings.edit')->get('user/settings', 'Auth\UserSettingsController@edit');
        Route::name('user_settings.update')->put('user/settings', 'Auth\UserSettingsController@update');

        Route::name('logout')->post('logout', 'Auth\LoginController@logout');

        Route::resource('categories', 'CategoryController');

        Route::name('series.thumb_asset')->get('series/{serie}/thumb_asset', 'SeriesController@thumbAsset');
        Route::name('series.thumb_small_asset')->get('series/{serie}/thumb_small_asset', 'SeriesController@thumbSmallAsset');
        Route::resource('series', 'SeriesController');
        #Route::model('series', \CodeFlix\Models\Serie::class);
        Route::resource('users', 'UsersController');

        Route::group(['prefix' => 'videos', 'as' => 'videos.'], function () {
            Route::name('relations.create')->get('{video}/relations', 'VideoRelationsController@create');
            Route::name('relations.store')->post('{video}/relations', 'VideoRelationsController@store');

            Route::name('uploads.create')->get('{video}/uploads', 'VideoUploadsController@create');
            Route::name('uploads.store')->post('{video}/uploads', 'VideoUploadsController@store');
        });

        Route::name('videos.file_asset')->get('videos/{video}/file_asset', 'VideosController@fileAsset');
        Route::name('videos.thumb_asset')->get('videos/{video}/thumb_asset', 'VideosController@thumbAsset');
        Route::name('videos.thumb_small_asset')->get('videos/{video}/thumb_small_asset', 'VideosController@thumbSmallAsset');
        Route::resource('videos', 'VideosController');
    });
});

Route::get('force-login', function(){
    \Auth::LoginUsingId(1);
});

app/Models/Video.php
<?php

namespace CodeFlix\Models;

use Bootstrapper\Interfaces\TableInterface;
use CodeFlix\Media\VideoPaths;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Video extends Model implements Transformable, TableInterface
{
    use TransformableTrait;
    use VideoPaths;
    use SoftDeletes;

    protected $fillable = [
        'title',
        'description',
        'duration',
        'published',
        'serie_id',
    ];

    protected $casts = [
        'completed' => 'boolean',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function serie()
    {
        return $this->belongsTo(Serie::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * @return array
     */
    public function getTableHeaders()
    {
        return ['#'];
    }

    public function getValueForHeader($header)
    {
        switch($header) {
            case '#':
                return $this->id;
                break;
        }
    }

}

app/Http/Controllers/Admin/VideosController.php
<?php

namespace CodeFlix\Http\Controllers\Admin;

use CodeFlix\Forms\VideoForm;
use CodeFlix\Http\Controllers\Controller;
use CodeFlix\Models\Video;
use CodeFlix\Repositories\VideoRepository;
use Illuminate\Http\Request;

class VideosController extends Controller
{
    /**
     * @var VideoRepository
     */
    private $repository;

    /**
     * @param VideoRepository $repository
     */
    public function __construct(VideoRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = $this->repository->paginate();

        return view('admin.videos.index', compact('videos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = \FormBuilder::create(VideoForm::class, [
            'url' => route('admin.videos.store'),
            'method' => 'POST'
        ]);

        return view('admin.videos.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response|RedirectResponse
     */
    public function store(Request $request)
    {
        /** @var Form $form */
        $form = \FormBuilder::create(VideoForm::class);

        if(!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->getFieldValues();

        $this->repository->create($data);

        $request->session()->flash('message', 'Video criado com sucesso.');

        return redirect()->route('admin.videos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \CodeFlix\Models\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show(Video $video)
    {
        return view('admin.videos.show', compact('video'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \CodeFlix\Models\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        $form = \FormBuilder::create(VideoForm::class, [
            'url' => route('admin.videos.update', ['video' => $video->id]),
            'method' => 'PUT',
            'model' => $video
        ]);

        return view('admin.videos.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \CodeFlix\Models\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /** @var \Form $form */
        $form = \FormBuilder::create(VideoForm::class, [
            'data' => ['id' => $id]
        ]);

        if(!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->getFieldValues();
        $this->repository->update($data, $id);

        $request->session()->flash('message', 'Video alterado com sucesso.');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \CodeFlix\Models\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        return route('admin.videos.index');
    }

    /**
     * @param Video $video
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function fileAsset(Video $video)
    {
        return response()->download($video->file_path);
    }

    public function thumbAsset(Video $video)
    {
        return response()->download($video->thumb_path);
    }

    public function thumbSmallAsset(Video $video)
    {
        return response()->download($video->thumb_small_path);
    }
    
}

resources/views/admin/videos/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        @component('admin.videos.tabs-component')
            <div class="col-md-12">
            <h4>Novo vídeo</h4>
               <?php $icon = Icon::create('floppy-disk'); ?>

                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' =>'btn btn-primary btn-block'],
                    'label' => $icon
                ])) !!}
            </div>
        @endcomponent
    </div>
</div>
@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            @component('admin.videos.tabs-component', ['video' => $form->getModel()])
                <div class="col-md-12">
                    <h4>Editar vídeo</h4>
                    <?php $icon = Icon::create('pencil'); ?>

                    {!! form($form->add('salvar', 'submit', [
                        'attr' => ['class' =>'btn btn-primary btn-block'],
                        'label' => $icon
                    ])) !!}

                    @endcomponent

                </div>
        </div>
@endsection

resources/views/admin/videos/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Listagem de Vídeos</h3>
        {!! Button::primary('Novo Vídeo')->asLinkTo(route('admin.videos.create')) !!}
    </div>
    <div class="row">
       {!!
            Table::withContents($videos->items())->striped()

            ->callback('Descrição', function($field, $video) {
                return MediaObject::withContents(
                    [
                        'image' => $video->thumb_small_asset,
                        'link' => $video->file_asset,
                        'heading' => $video->title,
                        'body' => $video->description
                    ]
                );
            })

            ->callback('Ações', function($field, $video) {
                $linkEdit = route('admin.videos.edit', ['video' => $video->id]);
                $linkShow = route('admin.videos.show', ['video' => $video->id]);
                return Button::link(Icon::create('pencil'))->asLinkTo($linkEdit).'|'.
                        Button::link(Icon::create('remove'))->asLinkTo($linkShow);
            })
        !!}

        {!! $videos->links() !!}
    </div>
</div>
@endsection

@push('styles')
<style type="text/css">
    .media-body {
        width: auto;
    }
</style>
@endpush

resources/views/admin/videos/relation.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        @component('admin.videos.tabs-component', ['video' => $form->getModel()])
            <div class="col-md-12">
            <h4>Série e categorias</h4>
               <?php $icon = Icon::create('pencil'); ?>

                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' =>'btn btn-primary btn-block'],
                    'label' => $icon
                ])) !!}
            </div>
        @endcomponent
    </div>
</div>
@endsection

resources/views/admin/videos/show.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="row">
        <h3>Ver vídeo</h3>

        <?php $iconEdit = Icon::create('pencil'); ?>
        {!! Button::primary($iconEdit)->asLinkTo(route('admin.videos.edit', ['video' => $video->id]))  !!}

        <?php $iconRemove = Icon::create('remove'); ?>
        {!! Button::danger($iconRemove)
                    ->asLinkTo(route('admin.videos.destroy', ['video' => $video->id]))
                    ->addAttributes(['onclick' => 'event.preventDefault(); document.getElementById("form-delete").submit();'])
        !!}

        <?php $formDelete = FormBuilder::plain([
            'id' => 'form-delete',
            'route' => ['admin.videos.destroy', 'video' => $video->id],
            'method' => 'DELETE',
            'style' => 'display:none'
        ]); ?>

        {!! form($formDelete) !!}

        <br /><br />

        <table class="table table-bordered">
            <tbody>
            <tr>
                <th scope="row">Thumb</th>
                <td><img src="{{$video->thumb_asset}}" width="512" height="360"/> </td>
            </tr>

            <tr>
                <th scope="row">Vídeo</th>
                <td><a href="{{ $video->file_asset }}" target="_blank"> Download</a> </td>
            </tr>

            <tr>
                <th scope="row">#</th>
                <td>{{ $video->id }}</td>
            </tr>
            <tr>
                <th scope="row">Título</th>
                <td>{{ $video->title }}</td>
            </tr>

            <tr>
                <th scope="row">Descrição</th>
                <td>{{ $video->description }}</td>
            </tr>
            </tbody>
        </table>

    </div>
</div>
@endsection

resources/views/admin/videos/tabs-component.blade.php
<?php
    $tabs = [
        [
            'title' => 'Informações',
            'link' => !isset($video) ? route('admin.videos.create') : route('admin.videos.edit', ['video' => $video->id])
        ],
        [
            'title' => 'Série e categorias',
            'link' => !isset($video) ? '#' : route('admin.videos.relations.create', ['video' => $video]),
            'disabled' => !isset($video) ? true : false
        ],
        [
            'title' => 'Vídeo e thumbnail',
            'link' => !isset($video) ? '#' : route('admin.videos.uploads.create', ['video' => $video]),
            'disabled' => !isset($video) ? true : false
        ],

    ];
?>

<h3>Gerenciar vídeo</h3>
<div class="text-right"> {!! Button::link('Listar vídeos')->aslinkTo(route('admin.videos.index')) !!}</div>
{!! Navigation::tabs($tabs) !!}
<div>
    {!! $slot !!}
</div>

resources/views/admin/videos/upload.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        @component('admin.videos.tabs-component', ['video' => $form->getModel()])
            <div class="col-md-12">
            <h4>Thumnail e arquivo de vídeo</h4>
               <?php $icon = Icon::create('pencil'); ?>

                {!! form($form->add('salvar', 'submit', [
                    'attr' => ['class' =>'btn btn-primary btn-block'],
                    'label' => $icon
                ])) !!}
            </div>
        @endcomponent
    </div>
</div>
@endsection