routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

#Auth::routes();

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

Route::get('/home', 'HomeController@index');

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin\\'
], function() {
    Route::name('login')->get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login');

    Route::group(['middleware' => ['isVerified', 'can:admin']], function (){
        Route::get('dashboard', function () {
            return view('admin.dashboard');
        });

        Route::name('user_settings.edit')->get('user/settings', 'Auth\UserSettingsController@edit');
        Route::name('user_settings.update')->put('user/settings', 'Auth\UserSettingsController@update');

        Route::name('logout')->post('logout', 'Auth\LoginController@logout');

        Route::resource('categories', 'CategoryController');

        Route::name('series.thumb_asset')->get('series/{serie}/thumb_asset', 'SeriesController@thumbAsset');
        Route::name('series.thumb_small_asset')->get('series/{serie}/thumb_small_asset', 'SeriesController@thumbSmallAsset');
        Route::resource('series', 'SeriesController');
        #Route::model('series', \CodeFlix\Models\Serie::class);
        Route::resource('users', 'UsersController');

        Route::group(['prefix' => 'videos', 'as' => 'videos.'], function () {
            Route::name('relations.create')->get('{video}/relations', 'VideoRelationsController@create');
            Route::name('relations.store')->post('{video}/relations', 'VideoRelationsController@store');

            Route::name('uploads.create')->get('{video}/uploads', 'VideoUploadsController@create');
            Route::name('uploads.store')->post('{video}/uploads', 'VideoUploadsController@store');
        });

        Route::name('videos.file_asset')->get('videos/{video}/file_asset', 'VideosController@fileAsset');
        Route::name('videos.thumb_asset')->get('videos/{video}/thumb_asset', 'VideosController@thumbAsset');
        Route::name('videos.thumb_small_asset')->get('videos/{video}/thumb_small_asset', 'VideosController@thumbSmallAsset');
        Route::resource('videos', 'VideosController');
    });
});

Route::get('force-login', function(){
    \Auth::LoginUsingId(1);
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    @stack('styles')
</head>
<body>
    <div id="app">
        <?php
            $navbar = Navbar::withBrand(config('app.name'), url('/admin/dashboard'))->inverse();
            if(Auth::check()) {
                $arrayLinks = [
                    ['link' => route('admin.users.index'), 'title' => 'Usuário'],
                    ['link' => route('admin.categories.index'), 'title' => 'Categorias'],

                ];

                $menus = Navigation::links($arrayLinks);
                $logout = Navigation::links(
                [
                    [
                        Auth::user()->name,
                        [
                            [
                                'link' => route('admin.logout'),
                                'title' => 'Logout',
                                'linkAttributes' => ['onclick' => 'event.preventDefault(); document.getElementById("form-logout").submit();']
                            ],
                            [
                                'link' => route('admin.user_settings.edit'),
                                'title' => 'Mudar senha',
                            ],
                        ]
                    ]
                ])->right();
                $navbar->withContent($menus)->withContent($logout);
            }
        ?>

        {!! $navbar !!}

        <?php $formLogout = FormBuilder::plain([
                'id' => 'form-logout',
                'route' => ['admin.logout'],
                'method' => 'POST',
                'style' => 'display:none'
        ]); ?>

        {!! form($formLogout) !!}


        @if(Session::has('message'))
            <div class="container">
                {!! Alert::success(Session::get('message'))->close() !!}
            </div>
        @endif

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('admin.login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>